# Generated by Django 5.2.6 on 2025-09-22 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('institute', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mentors/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('enrolment_no', models.CharField(max_length=50, unique=True)),
                ('current_cgpa', models.FloatField(default=0.0, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('attendance', models.FloatField()),
                ('avg_test_score', models.FloatField()),
                ('attempts', models.IntegerField(default=0, null=True)),
                ('fees_paid', models.FloatField()),
                ('backlogs', models.IntegerField(default=0, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('predicted_label', models.CharField(blank=True, max_length=10, null=True)),
                ('prediction_percentage', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('prediction', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('academic_session', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor_name', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='dropout_backend.studentrecord')),
            ],
        ),
    ]
