# Generated by Django 5.2.6 on 2025-09-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropout_backend', '0002_mentor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='dropout_backend.profile'),
        ),
    ]
