# Generated by Django 5.2.6 on 2025-09-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropout_backend', '0003_studentrecord_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='enrolment_no',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='guardian_contact',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
