# Generated by Django 5.2.6 on 2025-09-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropout_backend', '0004_studentrecord_batch_alter_studentrecord_enrolment_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
