# Generated by Django 5.2.6 on 2025-09-23 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropout_backend', '0005_smsnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnotification',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
