# Generated by Django 5.2.6 on 2025-09-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropout_backend', '0007_emailnotification_delete_smsnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='st_id',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
