# Generated by Django 5.2.6 on 2025-09-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropout_backend', '0008_alter_studentrecord_st_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='enrolment_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='studentrecord',
            unique_together={('enrolment_no', 'mentor')},
        ),
    ]
